[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/widget"
  to = "/gigwidget.html"
  status = 200

[[redirects]]
  from = "/widget/*"
  to = "/gigwidget.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200